version: '3.4'

services:
  quizappdb:
    container_name: "quizappdb"
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: on-failure
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=quizappPaassword123@  

  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
    - 7039:8080
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=Server=quizappdb,1433;User ID = sa;Password=quizappPaassword123@;TrustServerCertificate=true
      - OpenAiApiKey=YOUROPENAIAPIKEY
      - ASPNETCORE_URLS=http://+:8080